function(expand_target_libs target_names expanded_list)
    set(scoped_list)
    foreach(target_name ${target_names})
        if(TARGET ${target_name})
            get_target_property(target_libs  ${target_name} INTERFACE_LINK_LIBRARIES)
#            message("Iterating through: ${target_libs}")
            foreach(lib ${target_libs})
                if(TARGET ${lib})
                    expand_target_libs(${lib} ${expanded_list})
                else()
                    list(APPEND scoped_list ${lib})
                endif()
            endforeach()
        else()
            list(APPEND scoped_list ${target_name})
        endif()
    endforeach()
    #            message("Current scoped_list: ${scoped_list}")
    #            message("Current ${expanded_list}: ${${expanded_list}}")
    #            message("Returning:  ${scoped_list};${${expanded_list}}")
    if(NOT ${expanded_list})
        set(${expanded_list} "${scoped_list}" PARENT_SCOPE)
    else()
        set(${expanded_list} "${scoped_list};${${expanded_list}}" PARENT_SCOPE)
    endif()
endfunction()




function(expand_target_incs target_names expanded_list)
    foreach(target_name ${target_names})
        if(TARGET ${target_name})
            get_target_property(target_libs  ${target_name} INTERFACE_LINK_LIBRARIES)
            get_target_property(found_incs   ${target_name} INTERFACE_INCLUDE_DIRECTORIES)
            foreach(lib ${target_libs})
                if(TARGET ${lib})
                    expand_target_incs(${lib} ${expanded_list})
                    get_target_property(incs ${lib} INTERFACE_INCLUDE_DIRECTORIES)
                    foreach(inc ${incs})
                        if(inc)
                            list(APPEND found_incs ${inc})
                        endif()
                    endforeach()
                endif()
            endforeach()

        #    set(target_incs)
            foreach(inc ${found_incs})
                if(inc)
                    list(APPEND target_incs ${inc})
                endif()
            endforeach()

        #    message("Current target_incs: ${target_incs}")
        #    message("Current ${expanded_list}: ${${expanded_list}}")
        #    message("Returning:  ${${expanded_list}};${target_incs}")
            if(NOT ${expanded_list})
                set(${expanded_list} "${target_incs}" PARENT_SCOPE)
            else()
                set(${expanded_list} "${${expanded_list}};${target_incs}" PARENT_SCOPE)
            endif()
        endif()
    endforeach()
endfunction()




function(expand_target_opts target_names expanded_list)
    foreach(target_name ${target_names})
        if(TARGET ${target_name})
            get_target_property(target_libs  ${target_name} INTERFACE_LINK_LIBRARIES)
            get_target_property(found_opts  ${target_name} INTERFACE_COMPILE_OPTIONS)
            foreach(lib ${target_libs})
                if(TARGET ${lib})
                    expand_target_opts(${lib} ${expanded_list})
                    get_target_property(opts ${lib} INTERFACE_COMPILE_OPTIONS)
                    foreach(opt ${opts})
                        if(opt)
                            list(APPEND found_opts ${opt})
                        endif()
                    endforeach()
                endif()
            endforeach()
            foreach(opt ${found_opts})
                if(opt)
                    list(APPEND target_opts ${opt})
                endif()
            endforeach()
        #    message("Current target_opts: ${target_opts}")
        #    message("Current ${expanded_list}: ${${expanded_list}}")
        #    message("Returning:  ${${expanded_list}};${target_opts}")
            if(NOT ${expanded_list})
                set(${expanded_list} "${target_opts}" PARENT_SCOPE)
            else()
                set(${expanded_list} "${${expanded_list}};${target_opts}" PARENT_SCOPE)
            endif()
        endif()
    endforeach()
endfunction()