name: Mirror at KTH-condmat
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    environment: CMT-mirror
    steps:
      - name: Sync to KTH-condmat/CMT
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "DavidAce/CMT"
          source_branch: "master"
          destination_repo: "https://DavidAce:${{ secrets.CMT_ACCESS_TOKEN }}@github.com/KTH-condmat/CMT.git"
          destination_branch: "main"